# Generated by Django 5.1.1 on 2024-09-22 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Hotel",
            fields=[
                ("HotelID", models.IntegerField(primary_key=True, serialize=False)),
                ("Name", models.CharField(max_length=255)),
                ("Location", models.CharField(max_length=255)),
                ("Description", models.TextField()),
                ("StarRating", models.IntegerField()),
                ("Amenities", models.TextField()),
                ("ContactInfo", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=255, unique=True)),
                ("username", models.CharField(max_length=50, unique=True)),
                ("preferences", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("RoomID", models.IntegerField()),
                ("RoomType", models.CharField(max_length=50)),
                ("Price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("Availability", models.BooleanField()),
                ("Features", models.TextField()),
                (
                    "Hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rooms",
                        to="hotel.hotel",
                    ),
                ),
            ],
            options={
                "unique_together": {("RoomID", "Hotel")},
            },
        ),
    ]
