# Generated by Django 5.1.1 on 2024-09-22 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotel", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="preferences",
        ),
        migrations.AddField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=128, null=True),
        ),
    ]
