# Generated by Django 5.1.1 on 2024-09-22 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotel", "0004_remove_user_created_at_user_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(max_length=13),
        ),
    ]
