# Generated by Django 5.1.1 on 2024-09-22 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotel", "0005_alter_user_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hotel",
            name="HotelID",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
